# Generated by ariadne-codegen
# Source: runpod.schema

from enum import Enum


class BillingGranularity(str, Enum):
    HOURLY = "HOURLY"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class ClientCreditChargeType(str, Enum):
    CHARGE_SERVERLESS = "CHARGE_SERVERLESS"
    CHARGE_POD = "CHARGE_POD"
    CHARGE_API = "CHARGE_API"
    CHARGE_STORAGE = "CHARGE_STORAGE"
    CHARGE_SAVINGS_PLAN = "CHARGE_SAVINGS_PLAN"


class CloudTypeEnum(str, Enum):
    SECURE = "SECURE"
    COMMUNITY = "COMMUNITY"
    ALL = "ALL"


class Compliance(str, Enum):
    GDPR = "GDPR"
    ISO_IEC_27001 = "ISO_IEC_27001"
    ISO_14001 = "ISO_14001"
    PCI_DSS = "PCI_DSS"
    HITRUST = "HITRUST"
    SOC_1_TYPE_2 = "SOC_1_TYPE_2"
    SOC_2_TYPE_2 = "SOC_2_TYPE_2"
    SOC_3_TYPE_2 = "SOC_3_TYPE_2"
    ITAR = "ITAR"
    FISMA_HIGH = "FISMA_HIGH"


class ComputeType(str, Enum):
    CPU = "CPU"
    GPU = "GPU"


class CsrRole(str, Enum):
    admin = "admin"
    support_write = "support_write"
    support_read = "support_read"


class DiscountType(str, Enum):
    SERVERLESS = "SERVERLESS"


class EndpointStatisticGranularity(str, Enum):
    LIVE = "LIVE"
    HOURLY = "HOURLY"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class PodStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    RESTARTING = "RESTARTING"
    EXITED = "EXITED"
    PAUSED = "PAUSED"
    DEAD = "DEAD"
    TERMINATED = "TERMINATED"


class PodType(str, Enum):
    INTERRUPTABLE = "INTERRUPTABLE"
    RESERVED = "RESERVED"
    BID = "BID"
    BACKGROUND = "BACKGROUND"


class Scope(str, Enum):
    CSR_ADMIN = "CSR_ADMIN"
    CSR_IMPERSONATION = "CSR_IMPERSONATION"
    CSR_READ = "CSR_READ"
    CSR_WRITE = "CSR_WRITE"
    TEAM_ADMIN = "TEAM_ADMIN"
    TEAM_DEV = "TEAM_DEV"
    TEAM_BILLING = "TEAM_BILLING"
    TEAM_BASIC = "TEAM_BASIC"
    HOST = "HOST"


class TeamRole(str, Enum):
    owner = "owner"
    admin = "admin"
    member = "member"
    dev = "dev"
    billing = "billing"
    basic = "basic"


class TransactionMedium(str, Enum):
    STRIPE = "STRIPE"
    CRYPTO = "CRYPTO"
    RUNPOD = "RUNPOD"
    COINBASE = "COINBASE"
    WIRE = "WIRE"
    REFERRAL = "REFERRAL"


class TransactionType(str, Enum):
    RELOAD = "RELOAD"
    CREDIT = "CREDIT"
    DEBIT = "DEBIT"
    PAYOUT = "PAYOUT"


class UserServerlessBillingGroupBy(str, Enum):
    GPU_TYPE = "GPU_TYPE"
    ENDPOINT = "ENDPOINT"
    INSTANCE_ID = "INSTANCE_ID"
